AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless FastAPI on AWS Lambda

Globals:
  Function:
    Runtime: python3.9
    Timeout: 10
    MemorySize: 256

Resources:
  ApiBackend:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: fastapi_app.handler
      Events:
        ProxyApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods: ["*"]
        AllowOrigins: ["*"]

Outputs:
  ApiUrl:
    Description: "HTTP API endpoint URL"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
